/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IChainlinkPriceFeed,
  IChainlinkPriceFeedInterface,
} from "../../../contracts/interfaces/IChainlinkPriceFeed";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "feed",
        type: "address",
      },
    ],
    name: "FeedUpdate",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "oldAge",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newAge",
        type: "uint256",
      },
    ],
    name: "PriceAgeUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "oldAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "newAddress",
        type: "address",
      },
    ],
    name: "UpdatedExecutorAddress",
    type: "event",
  },
  {
    inputs: [],
    name: "decimals",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "backtrackRound",
        type: "uint64",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "getHistoricalPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "getPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "getPriceSafely",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "backtrackRound",
        type: "uint64",
      },
      {
        internalType: "address[]",
        name: "tokens",
        type: "address[]",
      },
    ],
    name: "removeHistoricalPrice",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "tokens",
        type: "address[]",
      },
      {
        internalType: "bytes[]",
        name: "updateData",
        type: "bytes[]",
      },
      {
        internalType: "uint64",
        name: "backtrackRound",
        type: "uint64",
      },
    ],
    name: "updateHistoricalPrice",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IChainlinkPriceFeed__factory {
  static readonly abi = _abi;
  static createInterface(): IChainlinkPriceFeedInterface {
    return new Interface(_abi) as IChainlinkPriceFeedInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IChainlinkPriceFeed {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IChainlinkPriceFeed;
  }
}
