/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IOraclePriceFeed,
  IOraclePriceFeedInterface,
} from "../../../contracts/interfaces/IOraclePriceFeed";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "oldAge",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newAge",
        type: "uint256",
      },
    ],
    name: "PriceAgeUpdated",
    type: "event",
  },
  {
    inputs: [],
    name: "decimals",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "backtrackRound",
        type: "uint64",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "getHistoricalPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "getPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "getPriceSafely",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "backtrackRound",
        type: "uint64",
      },
      {
        internalType: "address[]",
        name: "tokens",
        type: "address[]",
      },
    ],
    name: "removeHistoricalPrice",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "tokens",
        type: "address[]",
      },
      {
        internalType: "bytes[]",
        name: "updateData",
        type: "bytes[]",
      },
      {
        internalType: "uint64",
        name: "backtrackRound",
        type: "uint64",
      },
    ],
    name: "updateHistoricalPrice",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IOraclePriceFeed__factory {
  static readonly abi = _abi;
  static createInterface(): IOraclePriceFeedInterface {
    return new Interface(_abi) as IOraclePriceFeedInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IOraclePriceFeed {
    return new Contract(address, _abi, runner) as unknown as IOraclePriceFeed;
  }
}
