/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPoolTokenFactory,
  IPoolTokenFactoryInterface,
} from "../../../contracts/interfaces/IPoolTokenFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "indexToken",
        type: "address",
      },
      {
        internalType: "address",
        name: "stableToken",
        type: "address",
      },
    ],
    name: "createPoolToken",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPoolTokenFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IPoolTokenFactoryInterface {
    return new Interface(_abi) as IPoolTokenFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPoolTokenFactory {
    return new Contract(address, _abi, runner) as unknown as IPoolTokenFactory;
  }
}
