/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPoolView,
  IPoolViewInterface,
} from "../../../contracts/interfaces/IPoolView";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "oldAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "newAddress",
        type: "address",
      },
    ],
    name: "UpdatePool",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "oldAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "newAddress",
        type: "address",
      },
    ],
    name: "UpdatePositionManager",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_pairIndex",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_lpAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
    ],
    name: "getDepositAmount",
    outputs: [
      {
        internalType: "uint256",
        name: "depositIndexAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "depositStableAmount",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_pairIndex",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_indexAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_stableAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
    ],
    name: "getMintLpAmount",
    outputs: [
      {
        internalType: "uint256",
        name: "mintAmount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "slipToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "slipAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "indexFeeAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "stableFeeAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "afterFeeIndexAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "afterFeeStableAmount",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_pairIndex",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_lpAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
    ],
    name: "getReceivedAmount",
    outputs: [
      {
        internalType: "uint256",
        name: "receiveIndexTokenAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "receiveStableTokenAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "feeAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "feeIndexTokenAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "feeStableTokenAmount",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_pairIndex",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
    ],
    name: "lpFairPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPoolView__factory {
  static readonly abi = _abi;
  static createInterface(): IPoolViewInterface {
    return new Interface(_abi) as IPoolViewInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IPoolView {
    return new Contract(address, _abi, runner) as unknown as IPoolView;
  }
}
