/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface TestCallBackInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addLiquidity"
      | "addLiquidityCallback"
      | "addLiquidityForAccount"
      | "removeLiquidity"
      | "removeLiquidityCallback"
      | "removeLiquidityForAccount"
      | "swapCallback"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addLiquidity",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addLiquidityCallback",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addLiquidityForAccount",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "removeLiquidity",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "removeLiquidityCallback",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeLiquidityForAccount",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swapCallback",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addLiquidityCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addLiquidityForAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeLiquidityCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeLiquidityForAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapCallback",
    data: BytesLike
  ): Result;
}

export interface TestCallBack extends BaseContract {
  connect(runner?: ContractRunner | null): TestCallBack;
  waitForDeployment(): Promise<this>;

  interface: TestCallBackInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addLiquidity: TypedContractMethod<
    [
      pool: AddressLike,
      indexToken: AddressLike,
      stableToken: AddressLike,
      indexAmount: BigNumberish,
      stableAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  addLiquidityCallback: TypedContractMethod<
    [
      indexToken: AddressLike,
      stableToken: AddressLike,
      amountIndex: BigNumberish,
      amountStable: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  addLiquidityForAccount: TypedContractMethod<
    [
      pool: AddressLike,
      indexToken: AddressLike,
      stableToken: AddressLike,
      receiver: AddressLike,
      indexAmount: BigNumberish,
      stableAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  removeLiquidity: TypedContractMethod<
    [
      pool: AddressLike,
      indexToken: AddressLike,
      stableToken: AddressLike,
      amount: BigNumberish,
      useETH: boolean
    ],
    [void],
    "nonpayable"
  >;

  removeLiquidityCallback: TypedContractMethod<
    [pairToken: AddressLike, amount: BigNumberish, data: BytesLike],
    [void],
    "nonpayable"
  >;

  removeLiquidityForAccount: TypedContractMethod<
    [
      pool: AddressLike,
      indexToken: AddressLike,
      stableToken: AddressLike,
      receiver: AddressLike,
      amount: BigNumberish,
      useETH: boolean
    ],
    [void],
    "nonpayable"
  >;

  swapCallback: TypedContractMethod<
    [
      indexToken: AddressLike,
      stableToken: AddressLike,
      indexAmount: BigNumberish,
      stableAmount: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addLiquidity"
  ): TypedContractMethod<
    [
      pool: AddressLike,
      indexToken: AddressLike,
      stableToken: AddressLike,
      indexAmount: BigNumberish,
      stableAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addLiquidityCallback"
  ): TypedContractMethod<
    [
      indexToken: AddressLike,
      stableToken: AddressLike,
      amountIndex: BigNumberish,
      amountStable: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addLiquidityForAccount"
  ): TypedContractMethod<
    [
      pool: AddressLike,
      indexToken: AddressLike,
      stableToken: AddressLike,
      receiver: AddressLike,
      indexAmount: BigNumberish,
      stableAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeLiquidity"
  ): TypedContractMethod<
    [
      pool: AddressLike,
      indexToken: AddressLike,
      stableToken: AddressLike,
      amount: BigNumberish,
      useETH: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeLiquidityCallback"
  ): TypedContractMethod<
    [pairToken: AddressLike, amount: BigNumberish, data: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeLiquidityForAccount"
  ): TypedContractMethod<
    [
      pool: AddressLike,
      indexToken: AddressLike,
      stableToken: AddressLike,
      receiver: AddressLike,
      amount: BigNumberish,
      useETH: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapCallback"
  ): TypedContractMethod<
    [
      indexToken: AddressLike,
      stableToken: AddressLike,
      indexAmount: BigNumberish,
      stableAmount: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
