/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface PoolViewInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADDRESS_PROVIDER"
      | "getDepositAmount"
      | "getMintLpAmount"
      | "getReceivedAmount"
      | "initialize"
      | "lpFairPrice"
      | "pool"
      | "positionManager"
      | "proxiableUUID"
      | "setPool"
      | "setPositionManager"
      | "upgradeTo"
      | "upgradeToAndCall"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminChanged"
      | "BeaconUpgraded"
      | "Initialized"
      | "UpdatePool"
      | "UpdatePositionManager"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADDRESS_PROVIDER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDepositAmount",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMintLpAmount",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReceivedAmount",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lpFairPrice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "pool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "positionManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPool",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPositionManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeTo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "ADDRESS_PROVIDER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDepositAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMintLpAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReceivedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lpFairPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "positionManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPositionManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "upgradeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
}

export namespace AdminChangedEvent {
  export type InputTuple = [previousAdmin: AddressLike, newAdmin: AddressLike];
  export type OutputTuple = [previousAdmin: string, newAdmin: string];
  export interface OutputObject {
    previousAdmin: string;
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BeaconUpgradedEvent {
  export type InputTuple = [beacon: AddressLike];
  export type OutputTuple = [beacon: string];
  export interface OutputObject {
    beacon: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdatePoolEvent {
  export type InputTuple = [
    sender: AddressLike,
    oldAddress: AddressLike,
    newAddress: AddressLike
  ];
  export type OutputTuple = [
    sender: string,
    oldAddress: string,
    newAddress: string
  ];
  export interface OutputObject {
    sender: string;
    oldAddress: string;
    newAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdatePositionManagerEvent {
  export type InputTuple = [
    sender: AddressLike,
    oldAddress: AddressLike,
    newAddress: AddressLike
  ];
  export type OutputTuple = [
    sender: string,
    oldAddress: string,
    newAddress: string
  ];
  export interface OutputObject {
    sender: string;
    oldAddress: string;
    newAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PoolView extends BaseContract {
  connect(runner?: ContractRunner | null): PoolView;
  waitForDeployment(): Promise<this>;

  interface: PoolViewInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADDRESS_PROVIDER: TypedContractMethod<[], [string], "view">;

  getDepositAmount: TypedContractMethod<
    [_pairIndex: BigNumberish, _lpAmount: BigNumberish, price: BigNumberish],
    [
      [bigint, bigint] & {
        depositIndexAmount: bigint;
        depositStableAmount: bigint;
      }
    ],
    "view"
  >;

  getMintLpAmount: TypedContractMethod<
    [
      _pairIndex: BigNumberish,
      _indexAmount: BigNumberish,
      _stableAmount: BigNumberish,
      price: BigNumberish
    ],
    [
      [bigint, string, bigint, bigint, bigint, bigint, bigint] & {
        mintAmount: bigint;
        slipToken: string;
        slipAmount: bigint;
        indexFeeAmount: bigint;
        stableFeeAmount: bigint;
        afterFeeIndexAmount: bigint;
        afterFeeStableAmount: bigint;
      }
    ],
    "view"
  >;

  getReceivedAmount: TypedContractMethod<
    [_pairIndex: BigNumberish, _lpAmount: BigNumberish, price: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        receiveIndexTokenAmount: bigint;
        receiveStableTokenAmount: bigint;
        feeAmount: bigint;
        feeIndexTokenAmount: bigint;
        feeStableTokenAmount: bigint;
      }
    ],
    "view"
  >;

  initialize: TypedContractMethod<
    [addressProvider: AddressLike],
    [void],
    "nonpayable"
  >;

  lpFairPrice: TypedContractMethod<
    [_pairIndex: BigNumberish, price: BigNumberish],
    [bigint],
    "view"
  >;

  pool: TypedContractMethod<[], [string], "view">;

  positionManager: TypedContractMethod<[], [string], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  setPool: TypedContractMethod<[_pool: AddressLike], [void], "nonpayable">;

  setPositionManager: TypedContractMethod<
    [_positionManager: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeTo: TypedContractMethod<
    [newImplementation: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADDRESS_PROVIDER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getDepositAmount"
  ): TypedContractMethod<
    [_pairIndex: BigNumberish, _lpAmount: BigNumberish, price: BigNumberish],
    [
      [bigint, bigint] & {
        depositIndexAmount: bigint;
        depositStableAmount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMintLpAmount"
  ): TypedContractMethod<
    [
      _pairIndex: BigNumberish,
      _indexAmount: BigNumberish,
      _stableAmount: BigNumberish,
      price: BigNumberish
    ],
    [
      [bigint, string, bigint, bigint, bigint, bigint, bigint] & {
        mintAmount: bigint;
        slipToken: string;
        slipAmount: bigint;
        indexFeeAmount: bigint;
        stableFeeAmount: bigint;
        afterFeeIndexAmount: bigint;
        afterFeeStableAmount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReceivedAmount"
  ): TypedContractMethod<
    [_pairIndex: BigNumberish, _lpAmount: BigNumberish, price: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        receiveIndexTokenAmount: bigint;
        receiveStableTokenAmount: bigint;
        feeAmount: bigint;
        feeIndexTokenAmount: bigint;
        feeStableTokenAmount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[addressProvider: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "lpFairPrice"
  ): TypedContractMethod<
    [_pairIndex: BigNumberish, price: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "pool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "positionManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setPool"
  ): TypedContractMethod<[_pool: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPositionManager"
  ): TypedContractMethod<[_positionManager: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeTo"
  ): TypedContractMethod<
    [newImplementation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getEvent(
    key: "AdminChanged"
  ): TypedContractEvent<
    AdminChangedEvent.InputTuple,
    AdminChangedEvent.OutputTuple,
    AdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "BeaconUpgraded"
  ): TypedContractEvent<
    BeaconUpgradedEvent.InputTuple,
    BeaconUpgradedEvent.OutputTuple,
    BeaconUpgradedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "UpdatePool"
  ): TypedContractEvent<
    UpdatePoolEvent.InputTuple,
    UpdatePoolEvent.OutputTuple,
    UpdatePoolEvent.OutputObject
  >;
  getEvent(
    key: "UpdatePositionManager"
  ): TypedContractEvent<
    UpdatePositionManagerEvent.InputTuple,
    UpdatePositionManagerEvent.OutputTuple,
    UpdatePositionManagerEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "AdminChanged(address,address)": TypedContractEvent<
      AdminChangedEvent.InputTuple,
      AdminChangedEvent.OutputTuple,
      AdminChangedEvent.OutputObject
    >;
    AdminChanged: TypedContractEvent<
      AdminChangedEvent.InputTuple,
      AdminChangedEvent.OutputTuple,
      AdminChangedEvent.OutputObject
    >;

    "BeaconUpgraded(address)": TypedContractEvent<
      BeaconUpgradedEvent.InputTuple,
      BeaconUpgradedEvent.OutputTuple,
      BeaconUpgradedEvent.OutputObject
    >;
    BeaconUpgraded: TypedContractEvent<
      BeaconUpgradedEvent.InputTuple,
      BeaconUpgradedEvent.OutputTuple,
      BeaconUpgradedEvent.OutputObject
    >;

    "Initialized(uint8)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "UpdatePool(address,address,address)": TypedContractEvent<
      UpdatePoolEvent.InputTuple,
      UpdatePoolEvent.OutputTuple,
      UpdatePoolEvent.OutputObject
    >;
    UpdatePool: TypedContractEvent<
      UpdatePoolEvent.InputTuple,
      UpdatePoolEvent.OutputTuple,
      UpdatePoolEvent.OutputObject
    >;

    "UpdatePositionManager(address,address,address)": TypedContractEvent<
      UpdatePositionManagerEvent.InputTuple,
      UpdatePositionManagerEvent.OutputTuple,
      UpdatePositionManagerEvent.OutputObject
    >;
    UpdatePositionManager: TypedContractEvent<
      UpdatePositionManagerEvent.InputTuple,
      UpdatePositionManagerEvent.OutputTuple,
      UpdatePositionManagerEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
