/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ChainlinkPriceFeedInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADDRESS_PROVIDER"
      | "PRICE_DECIMALS"
      | "backtrackTokenPrices"
      | "checkSequencerStatus"
      | "dataFeeds"
      | "decimals"
      | "executor"
      | "getHistoricalPrice"
      | "getPrice"
      | "getPriceSafely"
      | "getRoundData"
      | "latestRoundData"
      | "priceAge"
      | "removeHistoricalPrice"
      | "sequencerUptimeFeeds"
      | "setTokenConfig"
      | "updateExecutorAddress"
      | "updateHistoricalPrice"
      | "updatePriceAge"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeedUpdate"
      | "PriceAgeUpdated"
      | "UpdatedExecutorAddress"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADDRESS_PROVIDER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRICE_DECIMALS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "backtrackTokenPrices",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkSequencerStatus",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "dataFeeds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(functionFragment: "executor", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getHistoricalPrice",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPrice",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPriceSafely",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoundData",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "latestRoundData",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "priceAge", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeHistoricalPrice",
    values: [BigNumberish, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "sequencerUptimeFeeds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenConfig",
    values: [AddressLike[], AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "updateExecutorAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateHistoricalPrice",
    values: [AddressLike[], BytesLike[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePriceAge",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "ADDRESS_PROVIDER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PRICE_DECIMALS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "backtrackTokenPrices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkSequencerStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dataFeeds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "executor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getHistoricalPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPriceSafely",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoundData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "latestRoundData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "priceAge", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeHistoricalPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sequencerUptimeFeeds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateExecutorAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateHistoricalPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePriceAge",
    data: BytesLike
  ): Result;
}

export namespace FeedUpdateEvent {
  export type InputTuple = [asset: AddressLike, feed: AddressLike];
  export type OutputTuple = [asset: string, feed: string];
  export interface OutputObject {
    asset: string;
    feed: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceAgeUpdatedEvent {
  export type InputTuple = [oldAge: BigNumberish, newAge: BigNumberish];
  export type OutputTuple = [oldAge: bigint, newAge: bigint];
  export interface OutputObject {
    oldAge: bigint;
    newAge: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdatedExecutorAddressEvent {
  export type InputTuple = [
    sender: AddressLike,
    oldAddress: AddressLike,
    newAddress: AddressLike
  ];
  export type OutputTuple = [
    sender: string,
    oldAddress: string,
    newAddress: string
  ];
  export interface OutputObject {
    sender: string;
    oldAddress: string;
    newAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ChainlinkPriceFeed extends BaseContract {
  connect(runner?: ContractRunner | null): ChainlinkPriceFeed;
  waitForDeployment(): Promise<this>;

  interface: ChainlinkPriceFeedInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADDRESS_PROVIDER: TypedContractMethod<[], [string], "view">;

  PRICE_DECIMALS: TypedContractMethod<[], [bigint], "view">;

  backtrackTokenPrices: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  checkSequencerStatus: TypedContractMethod<
    [token: AddressLike],
    [void],
    "view"
  >;

  dataFeeds: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  decimals: TypedContractMethod<[], [bigint], "view">;

  executor: TypedContractMethod<[], [string], "view">;

  getHistoricalPrice: TypedContractMethod<
    [publishTime: BigNumberish, token: AddressLike],
    [bigint],
    "view"
  >;

  getPrice: TypedContractMethod<[token: AddressLike], [bigint], "view">;

  getPriceSafely: TypedContractMethod<[token: AddressLike], [bigint], "view">;

  getRoundData: TypedContractMethod<
    [token: AddressLike, _roundId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        roundId: bigint;
        price: bigint;
        startedAt: bigint;
        updatedAt: bigint;
        answeredInRound: bigint;
      }
    ],
    "view"
  >;

  latestRoundData: TypedContractMethod<
    [token: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        roundId: bigint;
        price: bigint;
        startedAt: bigint;
        updatedAt: bigint;
        answeredInRound: bigint;
      }
    ],
    "view"
  >;

  priceAge: TypedContractMethod<[], [bigint], "view">;

  removeHistoricalPrice: TypedContractMethod<
    [_backtrackRound: BigNumberish, tokens: AddressLike[]],
    [void],
    "nonpayable"
  >;

  sequencerUptimeFeeds: TypedContractMethod<
    [arg0: AddressLike],
    [string],
    "view"
  >;

  setTokenConfig: TypedContractMethod<
    [assets: AddressLike[], feeds: AddressLike[]],
    [void],
    "nonpayable"
  >;

  updateExecutorAddress: TypedContractMethod<
    [newAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  updateHistoricalPrice: TypedContractMethod<
    [tokens: AddressLike[], arg1: BytesLike[], roundId: BigNumberish],
    [void],
    "payable"
  >;

  updatePriceAge: TypedContractMethod<
    [age: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADDRESS_PROVIDER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PRICE_DECIMALS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "backtrackTokenPrices"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "checkSequencerStatus"
  ): TypedContractMethod<[token: AddressLike], [void], "view">;
  getFunction(
    nameOrSignature: "dataFeeds"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "decimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "executor"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getHistoricalPrice"
  ): TypedContractMethod<
    [publishTime: BigNumberish, token: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPrice"
  ): TypedContractMethod<[token: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPriceSafely"
  ): TypedContractMethod<[token: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoundData"
  ): TypedContractMethod<
    [token: AddressLike, _roundId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        roundId: bigint;
        price: bigint;
        startedAt: bigint;
        updatedAt: bigint;
        answeredInRound: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "latestRoundData"
  ): TypedContractMethod<
    [token: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        roundId: bigint;
        price: bigint;
        startedAt: bigint;
        updatedAt: bigint;
        answeredInRound: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "priceAge"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "removeHistoricalPrice"
  ): TypedContractMethod<
    [_backtrackRound: BigNumberish, tokens: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sequencerUptimeFeeds"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "setTokenConfig"
  ): TypedContractMethod<
    [assets: AddressLike[], feeds: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateExecutorAddress"
  ): TypedContractMethod<[newAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateHistoricalPrice"
  ): TypedContractMethod<
    [tokens: AddressLike[], arg1: BytesLike[], roundId: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "updatePriceAge"
  ): TypedContractMethod<[age: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "FeedUpdate"
  ): TypedContractEvent<
    FeedUpdateEvent.InputTuple,
    FeedUpdateEvent.OutputTuple,
    FeedUpdateEvent.OutputObject
  >;
  getEvent(
    key: "PriceAgeUpdated"
  ): TypedContractEvent<
    PriceAgeUpdatedEvent.InputTuple,
    PriceAgeUpdatedEvent.OutputTuple,
    PriceAgeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "UpdatedExecutorAddress"
  ): TypedContractEvent<
    UpdatedExecutorAddressEvent.InputTuple,
    UpdatedExecutorAddressEvent.OutputTuple,
    UpdatedExecutorAddressEvent.OutputObject
  >;

  filters: {
    "FeedUpdate(address,address)": TypedContractEvent<
      FeedUpdateEvent.InputTuple,
      FeedUpdateEvent.OutputTuple,
      FeedUpdateEvent.OutputObject
    >;
    FeedUpdate: TypedContractEvent<
      FeedUpdateEvent.InputTuple,
      FeedUpdateEvent.OutputTuple,
      FeedUpdateEvent.OutputObject
    >;

    "PriceAgeUpdated(uint256,uint256)": TypedContractEvent<
      PriceAgeUpdatedEvent.InputTuple,
      PriceAgeUpdatedEvent.OutputTuple,
      PriceAgeUpdatedEvent.OutputObject
    >;
    PriceAgeUpdated: TypedContractEvent<
      PriceAgeUpdatedEvent.InputTuple,
      PriceAgeUpdatedEvent.OutputTuple,
      PriceAgeUpdatedEvent.OutputObject
    >;

    "UpdatedExecutorAddress(address,address,address)": TypedContractEvent<
      UpdatedExecutorAddressEvent.InputTuple,
      UpdatedExecutorAddressEvent.OutputTuple,
      UpdatedExecutorAddressEvent.OutputObject
    >;
    UpdatedExecutorAddress: TypedContractEvent<
      UpdatedExecutorAddressEvent.InputTuple,
      UpdatedExecutorAddressEvent.OutputTuple,
      UpdatedExecutorAddressEvent.OutputObject
    >;
  };
}
