/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IAddressesProviderInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "WETH"
      | "backtracker"
      | "executionLogic"
      | "fundingRate"
      | "indexPriceOracle"
      | "liquidationLogic"
      | "priceOracle"
      | "roleManager"
      | "timelock"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "AddressSet"): EventFragment;

  encodeFunctionData(functionFragment: "WETH", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "backtracker",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executionLogic",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fundingRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "indexPriceOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "liquidationLogic",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "priceOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "roleManager",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "timelock", values?: undefined): string;

  decodeFunctionResult(functionFragment: "WETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "backtracker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executionLogic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundingRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "indexPriceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidationLogic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "priceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "roleManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "timelock", data: BytesLike): Result;
}

export namespace AddressSetEvent {
  export type InputTuple = [
    id: BytesLike,
    oldAddress: AddressLike,
    newAddress: AddressLike
  ];
  export type OutputTuple = [
    id: string,
    oldAddress: string,
    newAddress: string
  ];
  export interface OutputObject {
    id: string;
    oldAddress: string;
    newAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IAddressesProvider extends BaseContract {
  connect(runner?: ContractRunner | null): IAddressesProvider;
  waitForDeployment(): Promise<this>;

  interface: IAddressesProviderInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  WETH: TypedContractMethod<[], [string], "view">;

  backtracker: TypedContractMethod<[], [string], "view">;

  executionLogic: TypedContractMethod<[], [string], "view">;

  fundingRate: TypedContractMethod<[], [string], "view">;

  indexPriceOracle: TypedContractMethod<[], [string], "view">;

  liquidationLogic: TypedContractMethod<[], [string], "view">;

  priceOracle: TypedContractMethod<[], [string], "view">;

  roleManager: TypedContractMethod<[], [string], "view">;

  timelock: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "WETH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "backtracker"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "executionLogic"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "fundingRate"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "indexPriceOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "liquidationLogic"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "priceOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "roleManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "timelock"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AddressSet"
  ): TypedContractEvent<
    AddressSetEvent.InputTuple,
    AddressSetEvent.OutputTuple,
    AddressSetEvent.OutputObject
  >;

  filters: {
    "AddressSet(bytes32,address,address)": TypedContractEvent<
      AddressSetEvent.InputTuple,
      AddressSetEvent.OutputTuple,
      AddressSetEvent.OutputObject
    >;
    AddressSet: TypedContractEvent<
      AddressSetEvent.InputTuple,
      AddressSetEvent.OutputTuple,
      AddressSetEvent.OutputObject
    >;
  };
}
