/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IConfigurationProviderInterface extends Interface {
  getFunction(
    nameOrSignature: "baseFundingRate" | "baseFundingRateMaximum"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "UpdateBaseFundingRate"
      | "UpdateBaseFundingRateMaximum"
      | "UpdateGovAddress"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "baseFundingRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "baseFundingRateMaximum",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "baseFundingRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "baseFundingRateMaximum",
    data: BytesLike
  ): Result;
}

export namespace UpdateBaseFundingRateEvent {
  export type InputTuple = [
    sender: AddressLike,
    pairIndex: BigNumberish,
    baseFundingRate: BigNumberish
  ];
  export type OutputTuple = [
    sender: string,
    pairIndex: bigint,
    baseFundingRate: bigint
  ];
  export interface OutputObject {
    sender: string;
    pairIndex: bigint;
    baseFundingRate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateBaseFundingRateMaximumEvent {
  export type InputTuple = [
    sender: AddressLike,
    pairIndex: BigNumberish,
    maxBaseFundingRate: BigNumberish
  ];
  export type OutputTuple = [
    sender: string,
    pairIndex: bigint,
    maxBaseFundingRate: bigint
  ];
  export interface OutputObject {
    sender: string;
    pairIndex: bigint;
    maxBaseFundingRate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateGovAddressEvent {
  export type InputTuple = [
    sender: AddressLike,
    oldAddress: AddressLike,
    newAddress: AddressLike
  ];
  export type OutputTuple = [
    sender: string,
    oldAddress: string,
    newAddress: string
  ];
  export interface OutputObject {
    sender: string;
    oldAddress: string;
    newAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IConfigurationProvider extends BaseContract {
  connect(runner?: ContractRunner | null): IConfigurationProvider;
  waitForDeployment(): Promise<this>;

  interface: IConfigurationProviderInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  baseFundingRate: TypedContractMethod<
    [pairIndex: BigNumberish],
    [bigint],
    "view"
  >;

  baseFundingRateMaximum: TypedContractMethod<
    [pairIndex: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "baseFundingRate"
  ): TypedContractMethod<[pairIndex: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "baseFundingRateMaximum"
  ): TypedContractMethod<[pairIndex: BigNumberish], [bigint], "view">;

  getEvent(
    key: "UpdateBaseFundingRate"
  ): TypedContractEvent<
    UpdateBaseFundingRateEvent.InputTuple,
    UpdateBaseFundingRateEvent.OutputTuple,
    UpdateBaseFundingRateEvent.OutputObject
  >;
  getEvent(
    key: "UpdateBaseFundingRateMaximum"
  ): TypedContractEvent<
    UpdateBaseFundingRateMaximumEvent.InputTuple,
    UpdateBaseFundingRateMaximumEvent.OutputTuple,
    UpdateBaseFundingRateMaximumEvent.OutputObject
  >;
  getEvent(
    key: "UpdateGovAddress"
  ): TypedContractEvent<
    UpdateGovAddressEvent.InputTuple,
    UpdateGovAddressEvent.OutputTuple,
    UpdateGovAddressEvent.OutputObject
  >;

  filters: {
    "UpdateBaseFundingRate(address,uint256,int256)": TypedContractEvent<
      UpdateBaseFundingRateEvent.InputTuple,
      UpdateBaseFundingRateEvent.OutputTuple,
      UpdateBaseFundingRateEvent.OutputObject
    >;
    UpdateBaseFundingRate: TypedContractEvent<
      UpdateBaseFundingRateEvent.InputTuple,
      UpdateBaseFundingRateEvent.OutputTuple,
      UpdateBaseFundingRateEvent.OutputObject
    >;

    "UpdateBaseFundingRateMaximum(address,uint256,uint256)": TypedContractEvent<
      UpdateBaseFundingRateMaximumEvent.InputTuple,
      UpdateBaseFundingRateMaximumEvent.OutputTuple,
      UpdateBaseFundingRateMaximumEvent.OutputObject
    >;
    UpdateBaseFundingRateMaximum: TypedContractEvent<
      UpdateBaseFundingRateMaximumEvent.InputTuple,
      UpdateBaseFundingRateMaximumEvent.OutputTuple,
      UpdateBaseFundingRateMaximumEvent.OutputObject
    >;

    "UpdateGovAddress(address,address,address)": TypedContractEvent<
      UpdateGovAddressEvent.InputTuple,
      UpdateGovAddressEvent.OutputTuple,
      UpdateGovAddressEvent.OutputObject
    >;
    UpdateGovAddress: TypedContractEvent<
      UpdateGovAddressEvent.InputTuple,
      UpdateGovAddressEvent.OutputTuple,
      UpdateGovAddressEvent.OutputObject
    >;
  };
}
