/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IPool {
  export type PairStruct = {
    pairIndex: BigNumberish;
    indexToken: AddressLike;
    stableToken: AddressLike;
    pairToken: AddressLike;
    enable: boolean;
    kOfSwap: BigNumberish;
    expectIndexTokenP: BigNumberish;
    maxUnbalancedP: BigNumberish;
    unbalancedDiscountRate: BigNumberish;
    addLpFeeP: BigNumberish;
    removeLpFeeP: BigNumberish;
  };

  export type PairStructOutput = [
    pairIndex: bigint,
    indexToken: string,
    stableToken: string,
    pairToken: string,
    enable: boolean,
    kOfSwap: bigint,
    expectIndexTokenP: bigint,
    maxUnbalancedP: bigint,
    unbalancedDiscountRate: bigint,
    addLpFeeP: bigint,
    removeLpFeeP: bigint
  ] & {
    pairIndex: bigint;
    indexToken: string;
    stableToken: string;
    pairToken: string;
    enable: boolean;
    kOfSwap: bigint;
    expectIndexTokenP: bigint;
    maxUnbalancedP: bigint;
    unbalancedDiscountRate: bigint;
    addLpFeeP: bigint;
    removeLpFeeP: bigint;
  };

  export type VaultStruct = {
    indexTotalAmount: BigNumberish;
    indexReservedAmount: BigNumberish;
    stableTotalAmount: BigNumberish;
    stableReservedAmount: BigNumberish;
    averagePrice: BigNumberish;
  };

  export type VaultStructOutput = [
    indexTotalAmount: bigint,
    indexReservedAmount: bigint,
    stableTotalAmount: bigint,
    stableReservedAmount: bigint,
    averagePrice: bigint
  ] & {
    indexTotalAmount: bigint;
    indexReservedAmount: bigint;
    stableTotalAmount: bigint;
    stableReservedAmount: bigint;
    averagePrice: bigint;
  };
}

export interface IFundingRateInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getFundingInterval"
      | "getFundingRate"
      | "getFundingRateV2"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "UpdateConfigurationProviderAddress"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getFundingInterval",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFundingRate",
    values: [IPool.PairStruct, IPool.VaultStruct, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFundingRateV2",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getFundingInterval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFundingRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFundingRateV2",
    data: BytesLike
  ): Result;
}

export namespace UpdateConfigurationProviderAddressEvent {
  export type InputTuple = [
    sender: AddressLike,
    oldAddress: AddressLike,
    newAddress: AddressLike
  ];
  export type OutputTuple = [
    sender: string,
    oldAddress: string,
    newAddress: string
  ];
  export interface OutputObject {
    sender: string;
    oldAddress: string;
    newAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IFundingRate extends BaseContract {
  connect(runner?: ContractRunner | null): IFundingRate;
  waitForDeployment(): Promise<this>;

  interface: IFundingRateInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFundingInterval: TypedContractMethod<
    [_pairIndex: BigNumberish],
    [bigint],
    "view"
  >;

  getFundingRate: TypedContractMethod<
    [pair: IPool.PairStruct, vault: IPool.VaultStruct, price: BigNumberish],
    [bigint],
    "view"
  >;

  getFundingRateV2: TypedContractMethod<
    [pool: AddressLike, pairIndex: BigNumberish, price: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getFundingInterval"
  ): TypedContractMethod<[_pairIndex: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getFundingRate"
  ): TypedContractMethod<
    [pair: IPool.PairStruct, vault: IPool.VaultStruct, price: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFundingRateV2"
  ): TypedContractMethod<
    [pool: AddressLike, pairIndex: BigNumberish, price: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "UpdateConfigurationProviderAddress"
  ): TypedContractEvent<
    UpdateConfigurationProviderAddressEvent.InputTuple,
    UpdateConfigurationProviderAddressEvent.OutputTuple,
    UpdateConfigurationProviderAddressEvent.OutputObject
  >;

  filters: {
    "UpdateConfigurationProviderAddress(address,address,address)": TypedContractEvent<
      UpdateConfigurationProviderAddressEvent.InputTuple,
      UpdateConfigurationProviderAddressEvent.OutputTuple,
      UpdateConfigurationProviderAddressEvent.OutputObject
    >;
    UpdateConfigurationProviderAddress: TypedContractEvent<
      UpdateConfigurationProviderAddressEvent.InputTuple,
      UpdateConfigurationProviderAddressEvent.OutputTuple,
      UpdateConfigurationProviderAddressEvent.OutputObject
    >;
  };
}
