/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IRiskReserveInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "decrease"
      | "increase"
      | "recharge"
      | "updateDaoAddress"
      | "updatePoolAddress"
      | "updatePositionManagerAddress"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "UpdatedDaoAddress"
      | "UpdatedPoolAddress"
      | "UpdatedPositionManagerAddress"
      | "Withdraw"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "decrease",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "increase",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recharge",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateDaoAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePoolAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePositionManagerAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "decrease", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "increase", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "recharge", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateDaoAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePoolAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePositionManagerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace UpdatedDaoAddressEvent {
  export type InputTuple = [
    sender: AddressLike,
    oldAddress: AddressLike,
    newAddress: AddressLike
  ];
  export type OutputTuple = [
    sender: string,
    oldAddress: string,
    newAddress: string
  ];
  export interface OutputObject {
    sender: string;
    oldAddress: string;
    newAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdatedPoolAddressEvent {
  export type InputTuple = [
    sender: AddressLike,
    oldAddress: AddressLike,
    newAddress: AddressLike
  ];
  export type OutputTuple = [
    sender: string,
    oldAddress: string,
    newAddress: string
  ];
  export interface OutputObject {
    sender: string;
    oldAddress: string;
    newAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdatedPositionManagerAddressEvent {
  export type InputTuple = [
    sender: AddressLike,
    oldAddress: AddressLike,
    newAddress: AddressLike
  ];
  export type OutputTuple = [
    sender: string,
    oldAddress: string,
    newAddress: string
  ];
  export interface OutputObject {
    sender: string;
    oldAddress: string;
    newAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawEvent {
  export type InputTuple = [
    sender: AddressLike,
    asset: AddressLike,
    amount: BigNumberish,
    to: AddressLike
  ];
  export type OutputTuple = [
    sender: string,
    asset: string,
    amount: bigint,
    to: string
  ];
  export interface OutputObject {
    sender: string;
    asset: string;
    amount: bigint;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IRiskReserve extends BaseContract {
  connect(runner?: ContractRunner | null): IRiskReserve;
  waitForDeployment(): Promise<this>;

  interface: IRiskReserveInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  decrease: TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  increase: TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  recharge: TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateDaoAddress: TypedContractMethod<
    [newAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  updatePoolAddress: TypedContractMethod<
    [newAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  updatePositionManagerAddress: TypedContractMethod<
    [newAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<
    [asset: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "decrease"
  ): TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "increase"
  ): TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recharge"
  ): TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateDaoAddress"
  ): TypedContractMethod<[newAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updatePoolAddress"
  ): TypedContractMethod<[newAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updatePositionManagerAddress"
  ): TypedContractMethod<[newAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [asset: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "UpdatedDaoAddress"
  ): TypedContractEvent<
    UpdatedDaoAddressEvent.InputTuple,
    UpdatedDaoAddressEvent.OutputTuple,
    UpdatedDaoAddressEvent.OutputObject
  >;
  getEvent(
    key: "UpdatedPoolAddress"
  ): TypedContractEvent<
    UpdatedPoolAddressEvent.InputTuple,
    UpdatedPoolAddressEvent.OutputTuple,
    UpdatedPoolAddressEvent.OutputObject
  >;
  getEvent(
    key: "UpdatedPositionManagerAddress"
  ): TypedContractEvent<
    UpdatedPositionManagerAddressEvent.InputTuple,
    UpdatedPositionManagerAddressEvent.OutputTuple,
    UpdatedPositionManagerAddressEvent.OutputObject
  >;
  getEvent(
    key: "Withdraw"
  ): TypedContractEvent<
    WithdrawEvent.InputTuple,
    WithdrawEvent.OutputTuple,
    WithdrawEvent.OutputObject
  >;

  filters: {
    "UpdatedDaoAddress(address,address,address)": TypedContractEvent<
      UpdatedDaoAddressEvent.InputTuple,
      UpdatedDaoAddressEvent.OutputTuple,
      UpdatedDaoAddressEvent.OutputObject
    >;
    UpdatedDaoAddress: TypedContractEvent<
      UpdatedDaoAddressEvent.InputTuple,
      UpdatedDaoAddressEvent.OutputTuple,
      UpdatedDaoAddressEvent.OutputObject
    >;

    "UpdatedPoolAddress(address,address,address)": TypedContractEvent<
      UpdatedPoolAddressEvent.InputTuple,
      UpdatedPoolAddressEvent.OutputTuple,
      UpdatedPoolAddressEvent.OutputObject
    >;
    UpdatedPoolAddress: TypedContractEvent<
      UpdatedPoolAddressEvent.InputTuple,
      UpdatedPoolAddressEvent.OutputTuple,
      UpdatedPoolAddressEvent.OutputObject
    >;

    "UpdatedPositionManagerAddress(address,address,address)": TypedContractEvent<
      UpdatedPositionManagerAddressEvent.InputTuple,
      UpdatedPositionManagerAddressEvent.OutputTuple,
      UpdatedPositionManagerAddressEvent.OutputObject
    >;
    UpdatedPositionManagerAddress: TypedContractEvent<
      UpdatedPositionManagerAddressEvent.InputTuple,
      UpdatedPositionManagerAddressEvent.OutputTuple,
      UpdatedPositionManagerAddressEvent.OutputObject
    >;

    "Withdraw(address,address,uint256,address)": TypedContractEvent<
      WithdrawEvent.InputTuple,
      WithdrawEvent.OutputTuple,
      WithdrawEvent.OutputObject
    >;
    Withdraw: TypedContractEvent<
      WithdrawEvent.InputTuple,
      WithdrawEvent.OutputTuple,
      WithdrawEvent.OutputObject
    >;
  };
}
