/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IExecution {
  export type ExecutePositionStruct = {
    positionKey: BytesLike;
    sizeAmount: BigNumberish;
    tier: BigNumberish;
    referralsRatio: BigNumberish;
    referralUserRatio: BigNumberish;
    referralOwner: AddressLike;
  };

  export type ExecutePositionStructOutput = [
    positionKey: string,
    sizeAmount: bigint,
    tier: bigint,
    referralsRatio: bigint,
    referralUserRatio: bigint,
    referralOwner: string
  ] & {
    positionKey: string;
    sizeAmount: bigint;
    tier: bigint;
    referralsRatio: bigint;
    referralUserRatio: bigint;
    referralOwner: string;
  };

  export type LiquidatePositionStruct = {
    token: AddressLike;
    updateData: BytesLike;
    updateFee: BigNumberish;
    backtrackRound: BigNumberish;
    positionKey: BytesLike;
    sizeAmount: BigNumberish;
    tier: BigNumberish;
    referralsRatio: BigNumberish;
    referralUserRatio: BigNumberish;
    referralOwner: AddressLike;
  };

  export type LiquidatePositionStructOutput = [
    token: string,
    updateData: string,
    updateFee: bigint,
    backtrackRound: bigint,
    positionKey: string,
    sizeAmount: bigint,
    tier: bigint,
    referralsRatio: bigint,
    referralUserRatio: bigint,
    referralOwner: string
  ] & {
    token: string;
    updateData: string;
    updateFee: bigint;
    backtrackRound: bigint;
    positionKey: string;
    sizeAmount: bigint;
    tier: bigint;
    referralsRatio: bigint;
    referralUserRatio: bigint;
    referralOwner: string;
  };
}

export declare namespace IExecutionLogic {
  export type ExecuteOrderStruct = {
    orderId: BigNumberish;
    tradeType: BigNumberish;
    isIncrease: boolean;
    tier: BigNumberish;
    referralsRatio: BigNumberish;
    referralUserRatio: BigNumberish;
    referralOwner: AddressLike;
  };

  export type ExecuteOrderStructOutput = [
    orderId: bigint,
    tradeType: bigint,
    isIncrease: boolean,
    tier: bigint,
    referralsRatio: bigint,
    referralUserRatio: bigint,
    referralOwner: string
  ] & {
    orderId: bigint;
    tradeType: bigint;
    isIncrease: boolean;
    tier: bigint;
    referralsRatio: bigint;
    referralUserRatio: bigint;
    referralOwner: string;
  };
}

export interface ExecutorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADDRESS_PROVIDER"
      | "cleanInvalidPositionOrders"
      | "needADL"
      | "paused"
      | "positionManager"
      | "setPaused"
      | "setPricesAndExecuteADLOrders"
      | "setPricesAndExecuteDecreaseLimitOrders"
      | "setPricesAndExecuteDecreaseMarketOrders"
      | "setPricesAndExecuteIncreaseLimitOrders"
      | "setPricesAndExecuteIncreaseMarketOrders"
      | "setPricesAndExecuteOrders"
      | "setPricesAndLiquidatePositions"
      | "setUnPaused"
      | "updatePositionManager"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ExecuteAdlOrder"
      | "ExecuteOrderError"
      | "ExecuteOrderV2"
      | "ExecutePositionError"
      | "InvalidOrder"
      | "Paused"
      | "Unpaused"
      | "UpdatePositionManager"
      | "ZeroPosition"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADDRESS_PROVIDER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cleanInvalidPositionOrders",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "needADL",
    values: [BigNumberish, boolean, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "positionManager",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "setPaused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setPricesAndExecuteADLOrders",
    values: [
      AddressLike[],
      BigNumberish[],
      BytesLike[],
      BigNumberish[],
      BigNumberish,
      IExecution.ExecutePositionStruct[],
      IExecutionLogic.ExecuteOrderStruct[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setPricesAndExecuteDecreaseLimitOrders",
    values: [
      AddressLike[],
      BigNumberish[],
      BytesLike[],
      BigNumberish[],
      IExecutionLogic.ExecuteOrderStruct[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setPricesAndExecuteDecreaseMarketOrders",
    values: [
      AddressLike[],
      BigNumberish[],
      BytesLike[],
      BigNumberish[],
      IExecutionLogic.ExecuteOrderStruct[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setPricesAndExecuteIncreaseLimitOrders",
    values: [
      AddressLike[],
      BigNumberish[],
      BytesLike[],
      BigNumberish[],
      IExecutionLogic.ExecuteOrderStruct[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setPricesAndExecuteIncreaseMarketOrders",
    values: [
      AddressLike[],
      BigNumberish[],
      BytesLike[],
      BigNumberish[],
      IExecutionLogic.ExecuteOrderStruct[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setPricesAndExecuteOrders",
    values: [
      AddressLike[],
      BigNumberish[],
      BytesLike[],
      BigNumberish[],
      IExecutionLogic.ExecuteOrderStruct[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setPricesAndLiquidatePositions",
    values: [
      AddressLike[],
      BigNumberish[],
      IExecution.LiquidatePositionStruct[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setUnPaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updatePositionManager",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "ADDRESS_PROVIDER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cleanInvalidPositionOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "needADL", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "positionManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPaused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPricesAndExecuteADLOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPricesAndExecuteDecreaseLimitOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPricesAndExecuteDecreaseMarketOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPricesAndExecuteIncreaseLimitOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPricesAndExecuteIncreaseMarketOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPricesAndExecuteOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPricesAndLiquidatePositions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUnPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePositionManager",
    data: BytesLike
  ): Result;
}

export namespace ExecuteAdlOrderEvent {
  export type InputTuple = [
    adlOrderIds: BigNumberish[],
    adlPositionKeys: BytesLike[],
    orders: BigNumberish[]
  ];
  export type OutputTuple = [
    adlOrderIds: bigint[],
    adlPositionKeys: string[],
    orders: bigint[]
  ];
  export interface OutputObject {
    adlOrderIds: bigint[];
    adlPositionKeys: string[];
    orders: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecuteOrderErrorEvent {
  export type InputTuple = [orderId: BigNumberish, errorMessage: string];
  export type OutputTuple = [orderId: bigint, errorMessage: string];
  export interface OutputObject {
    orderId: bigint;
    errorMessage: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecuteOrderV2Event {
  export type InputTuple = [
    account: AddressLike,
    orderId: BigNumberish,
    pairIndex: BigNumberish,
    tradeType: BigNumberish,
    collateral: BigNumberish,
    orderSize: BigNumberish,
    orderPrice: BigNumberish,
    executionSize: BigNumberish,
    executionPrice: BigNumberish,
    executedSize: BigNumberish,
    pnl: BigNumberish,
    tradingFee: BigNumberish,
    fundingFee: BigNumberish,
    paymentType: BigNumberish,
    networkFeeAmount: BigNumberish,
    flags: BigNumberish
  ];
  export type OutputTuple = [
    account: string,
    orderId: bigint,
    pairIndex: bigint,
    tradeType: bigint,
    collateral: bigint,
    orderSize: bigint,
    orderPrice: bigint,
    executionSize: bigint,
    executionPrice: bigint,
    executedSize: bigint,
    pnl: bigint,
    tradingFee: bigint,
    fundingFee: bigint,
    paymentType: bigint,
    networkFeeAmount: bigint,
    flags: bigint
  ];
  export interface OutputObject {
    account: string;
    orderId: bigint;
    pairIndex: bigint;
    tradeType: bigint;
    collateral: bigint;
    orderSize: bigint;
    orderPrice: bigint;
    executionSize: bigint;
    executionPrice: bigint;
    executedSize: bigint;
    pnl: bigint;
    tradingFee: bigint;
    fundingFee: bigint;
    paymentType: bigint;
    networkFeeAmount: bigint;
    flags: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutePositionErrorEvent {
  export type InputTuple = [positionKey: BytesLike, errorMessage: string];
  export type OutputTuple = [positionKey: string, errorMessage: string];
  export interface OutputObject {
    positionKey: string;
    errorMessage: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvalidOrderEvent {
  export type InputTuple = [
    sender: AddressLike,
    orderId: BigNumberish,
    message: string
  ];
  export type OutputTuple = [sender: string, orderId: bigint, message: string];
  export interface OutputObject {
    sender: string;
    orderId: bigint;
    message: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdatePositionManagerEvent {
  export type InputTuple = [
    sender: AddressLike,
    oldAddress: AddressLike,
    newAddress: AddressLike
  ];
  export type OutputTuple = [
    sender: string,
    oldAddress: string,
    newAddress: string
  ];
  export interface OutputObject {
    sender: string;
    oldAddress: string;
    newAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ZeroPositionEvent {
  export type InputTuple = [
    sender: AddressLike,
    account: AddressLike,
    pairIndex: BigNumberish,
    isLong: boolean,
    message: string
  ];
  export type OutputTuple = [
    sender: string,
    account: string,
    pairIndex: bigint,
    isLong: boolean,
    message: string
  ];
  export interface OutputObject {
    sender: string;
    account: string;
    pairIndex: bigint;
    isLong: boolean;
    message: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Executor extends BaseContract {
  connect(runner?: ContractRunner | null): Executor;
  waitForDeployment(): Promise<this>;

  interface: ExecutorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADDRESS_PROVIDER: TypedContractMethod<[], [string], "view">;

  cleanInvalidPositionOrders: TypedContractMethod<
    [positionKeys: BytesLike[]],
    [void],
    "nonpayable"
  >;

  needADL: TypedContractMethod<
    [
      pairIndex: BigNumberish,
      isLong: boolean,
      executionSize: BigNumberish,
      executionPrice: BigNumberish
    ],
    [[boolean, bigint] & { need: boolean; needADLAmount: bigint }],
    "view"
  >;

  paused: TypedContractMethod<[], [boolean], "view">;

  positionManager: TypedContractMethod<[], [string], "view">;

  setPaused: TypedContractMethod<[], [void], "nonpayable">;

  setPricesAndExecuteADLOrders: TypedContractMethod<
    [
      tokens: AddressLike[],
      prices: BigNumberish[],
      updateData: BytesLike[],
      publishTimes: BigNumberish[],
      pairIndex: BigNumberish,
      executePositions: IExecution.ExecutePositionStruct[],
      executeOrders: IExecutionLogic.ExecuteOrderStruct[]
    ],
    [void],
    "payable"
  >;

  setPricesAndExecuteDecreaseLimitOrders: TypedContractMethod<
    [
      tokens: AddressLike[],
      prices: BigNumberish[],
      updateData: BytesLike[],
      publishTimes: BigNumberish[],
      decreaseOrders: IExecutionLogic.ExecuteOrderStruct[]
    ],
    [void],
    "payable"
  >;

  setPricesAndExecuteDecreaseMarketOrders: TypedContractMethod<
    [
      tokens: AddressLike[],
      prices: BigNumberish[],
      updateData: BytesLike[],
      publishTimes: BigNumberish[],
      decreaseOrders: IExecutionLogic.ExecuteOrderStruct[]
    ],
    [void],
    "payable"
  >;

  setPricesAndExecuteIncreaseLimitOrders: TypedContractMethod<
    [
      tokens: AddressLike[],
      prices: BigNumberish[],
      updateData: BytesLike[],
      publishTimes: BigNumberish[],
      increaseOrders: IExecutionLogic.ExecuteOrderStruct[]
    ],
    [void],
    "payable"
  >;

  setPricesAndExecuteIncreaseMarketOrders: TypedContractMethod<
    [
      tokens: AddressLike[],
      prices: BigNumberish[],
      updateData: BytesLike[],
      publishTimes: BigNumberish[],
      increaseOrders: IExecutionLogic.ExecuteOrderStruct[]
    ],
    [void],
    "payable"
  >;

  setPricesAndExecuteOrders: TypedContractMethod<
    [
      tokens: AddressLike[],
      prices: BigNumberish[],
      updateData: BytesLike[],
      publishTimes: BigNumberish[],
      orders: IExecutionLogic.ExecuteOrderStruct[]
    ],
    [void],
    "payable"
  >;

  setPricesAndLiquidatePositions: TypedContractMethod<
    [
      _tokens: AddressLike[],
      _prices: BigNumberish[],
      liquidatePositions: IExecution.LiquidatePositionStruct[]
    ],
    [void],
    "payable"
  >;

  setUnPaused: TypedContractMethod<[], [void], "nonpayable">;

  updatePositionManager: TypedContractMethod<
    [_positionManager: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADDRESS_PROVIDER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cleanInvalidPositionOrders"
  ): TypedContractMethod<[positionKeys: BytesLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "needADL"
  ): TypedContractMethod<
    [
      pairIndex: BigNumberish,
      isLong: boolean,
      executionSize: BigNumberish,
      executionPrice: BigNumberish
    ],
    [[boolean, bigint] & { need: boolean; needADLAmount: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "positionManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setPaused"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPricesAndExecuteADLOrders"
  ): TypedContractMethod<
    [
      tokens: AddressLike[],
      prices: BigNumberish[],
      updateData: BytesLike[],
      publishTimes: BigNumberish[],
      pairIndex: BigNumberish,
      executePositions: IExecution.ExecutePositionStruct[],
      executeOrders: IExecutionLogic.ExecuteOrderStruct[]
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "setPricesAndExecuteDecreaseLimitOrders"
  ): TypedContractMethod<
    [
      tokens: AddressLike[],
      prices: BigNumberish[],
      updateData: BytesLike[],
      publishTimes: BigNumberish[],
      decreaseOrders: IExecutionLogic.ExecuteOrderStruct[]
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "setPricesAndExecuteDecreaseMarketOrders"
  ): TypedContractMethod<
    [
      tokens: AddressLike[],
      prices: BigNumberish[],
      updateData: BytesLike[],
      publishTimes: BigNumberish[],
      decreaseOrders: IExecutionLogic.ExecuteOrderStruct[]
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "setPricesAndExecuteIncreaseLimitOrders"
  ): TypedContractMethod<
    [
      tokens: AddressLike[],
      prices: BigNumberish[],
      updateData: BytesLike[],
      publishTimes: BigNumberish[],
      increaseOrders: IExecutionLogic.ExecuteOrderStruct[]
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "setPricesAndExecuteIncreaseMarketOrders"
  ): TypedContractMethod<
    [
      tokens: AddressLike[],
      prices: BigNumberish[],
      updateData: BytesLike[],
      publishTimes: BigNumberish[],
      increaseOrders: IExecutionLogic.ExecuteOrderStruct[]
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "setPricesAndExecuteOrders"
  ): TypedContractMethod<
    [
      tokens: AddressLike[],
      prices: BigNumberish[],
      updateData: BytesLike[],
      publishTimes: BigNumberish[],
      orders: IExecutionLogic.ExecuteOrderStruct[]
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "setPricesAndLiquidatePositions"
  ): TypedContractMethod<
    [
      _tokens: AddressLike[],
      _prices: BigNumberish[],
      liquidatePositions: IExecution.LiquidatePositionStruct[]
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "setUnPaused"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updatePositionManager"
  ): TypedContractMethod<[_positionManager: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ExecuteAdlOrder"
  ): TypedContractEvent<
    ExecuteAdlOrderEvent.InputTuple,
    ExecuteAdlOrderEvent.OutputTuple,
    ExecuteAdlOrderEvent.OutputObject
  >;
  getEvent(
    key: "ExecuteOrderError"
  ): TypedContractEvent<
    ExecuteOrderErrorEvent.InputTuple,
    ExecuteOrderErrorEvent.OutputTuple,
    ExecuteOrderErrorEvent.OutputObject
  >;
  getEvent(
    key: "ExecuteOrderV2"
  ): TypedContractEvent<
    ExecuteOrderV2Event.InputTuple,
    ExecuteOrderV2Event.OutputTuple,
    ExecuteOrderV2Event.OutputObject
  >;
  getEvent(
    key: "ExecutePositionError"
  ): TypedContractEvent<
    ExecutePositionErrorEvent.InputTuple,
    ExecutePositionErrorEvent.OutputTuple,
    ExecutePositionErrorEvent.OutputObject
  >;
  getEvent(
    key: "InvalidOrder"
  ): TypedContractEvent<
    InvalidOrderEvent.InputTuple,
    InvalidOrderEvent.OutputTuple,
    InvalidOrderEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "UpdatePositionManager"
  ): TypedContractEvent<
    UpdatePositionManagerEvent.InputTuple,
    UpdatePositionManagerEvent.OutputTuple,
    UpdatePositionManagerEvent.OutputObject
  >;
  getEvent(
    key: "ZeroPosition"
  ): TypedContractEvent<
    ZeroPositionEvent.InputTuple,
    ZeroPositionEvent.OutputTuple,
    ZeroPositionEvent.OutputObject
  >;

  filters: {
    "ExecuteAdlOrder(uint256[],bytes32[],uint256[])": TypedContractEvent<
      ExecuteAdlOrderEvent.InputTuple,
      ExecuteAdlOrderEvent.OutputTuple,
      ExecuteAdlOrderEvent.OutputObject
    >;
    ExecuteAdlOrder: TypedContractEvent<
      ExecuteAdlOrderEvent.InputTuple,
      ExecuteAdlOrderEvent.OutputTuple,
      ExecuteAdlOrderEvent.OutputObject
    >;

    "ExecuteOrderError(uint256,string)": TypedContractEvent<
      ExecuteOrderErrorEvent.InputTuple,
      ExecuteOrderErrorEvent.OutputTuple,
      ExecuteOrderErrorEvent.OutputObject
    >;
    ExecuteOrderError: TypedContractEvent<
      ExecuteOrderErrorEvent.InputTuple,
      ExecuteOrderErrorEvent.OutputTuple,
      ExecuteOrderErrorEvent.OutputObject
    >;

    "ExecuteOrderV2(address,uint256,uint256,uint8,int256,uint256,uint256,uint256,uint256,uint256,int256,uint256,int256,uint8,uint256,uint256)": TypedContractEvent<
      ExecuteOrderV2Event.InputTuple,
      ExecuteOrderV2Event.OutputTuple,
      ExecuteOrderV2Event.OutputObject
    >;
    ExecuteOrderV2: TypedContractEvent<
      ExecuteOrderV2Event.InputTuple,
      ExecuteOrderV2Event.OutputTuple,
      ExecuteOrderV2Event.OutputObject
    >;

    "ExecutePositionError(bytes32,string)": TypedContractEvent<
      ExecutePositionErrorEvent.InputTuple,
      ExecutePositionErrorEvent.OutputTuple,
      ExecutePositionErrorEvent.OutputObject
    >;
    ExecutePositionError: TypedContractEvent<
      ExecutePositionErrorEvent.InputTuple,
      ExecutePositionErrorEvent.OutputTuple,
      ExecutePositionErrorEvent.OutputObject
    >;

    "InvalidOrder(address,uint256,string)": TypedContractEvent<
      InvalidOrderEvent.InputTuple,
      InvalidOrderEvent.OutputTuple,
      InvalidOrderEvent.OutputObject
    >;
    InvalidOrder: TypedContractEvent<
      InvalidOrderEvent.InputTuple,
      InvalidOrderEvent.OutputTuple,
      InvalidOrderEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "UpdatePositionManager(address,address,address)": TypedContractEvent<
      UpdatePositionManagerEvent.InputTuple,
      UpdatePositionManagerEvent.OutputTuple,
      UpdatePositionManagerEvent.OutputObject
    >;
    UpdatePositionManager: TypedContractEvent<
      UpdatePositionManagerEvent.InputTuple,
      UpdatePositionManagerEvent.OutputTuple,
      UpdatePositionManagerEvent.OutputObject
    >;

    "ZeroPosition(address,address,uint256,bool,string)": TypedContractEvent<
      ZeroPositionEvent.InputTuple,
      ZeroPositionEvent.OutputTuple,
      ZeroPositionEvent.OutputObject
    >;
    ZeroPosition: TypedContractEvent<
      ZeroPositionEvent.InputTuple,
      ZeroPositionEvent.OutputTuple,
      ZeroPositionEvent.OutputObject
    >;
  };
}
