/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IPool {
  export type PairStruct = {
    pairIndex: BigNumberish;
    indexToken: AddressLike;
    stableToken: AddressLike;
    pairToken: AddressLike;
    enable: boolean;
    kOfSwap: BigNumberish;
    expectIndexTokenP: BigNumberish;
    maxUnbalancedP: BigNumberish;
    unbalancedDiscountRate: BigNumberish;
    addLpFeeP: BigNumberish;
    removeLpFeeP: BigNumberish;
  };

  export type PairStructOutput = [
    pairIndex: bigint,
    indexToken: string,
    stableToken: string,
    pairToken: string,
    enable: boolean,
    kOfSwap: bigint,
    expectIndexTokenP: bigint,
    maxUnbalancedP: bigint,
    unbalancedDiscountRate: bigint,
    addLpFeeP: bigint,
    removeLpFeeP: bigint
  ] & {
    pairIndex: bigint;
    indexToken: string;
    stableToken: string;
    pairToken: string;
    enable: boolean;
    kOfSwap: bigint;
    expectIndexTokenP: bigint;
    maxUnbalancedP: bigint;
    unbalancedDiscountRate: bigint;
    addLpFeeP: bigint;
    removeLpFeeP: bigint;
  };

  export type VaultStruct = {
    indexTotalAmount: BigNumberish;
    indexReservedAmount: BigNumberish;
    stableTotalAmount: BigNumberish;
    stableReservedAmount: BigNumberish;
    averagePrice: BigNumberish;
  };

  export type VaultStructOutput = [
    indexTotalAmount: bigint,
    indexReservedAmount: bigint,
    stableTotalAmount: bigint,
    stableReservedAmount: bigint,
    averagePrice: bigint
  ] & {
    indexTotalAmount: bigint;
    indexReservedAmount: bigint;
    stableTotalAmount: bigint;
    stableReservedAmount: bigint;
    averagePrice: bigint;
  };
}

export declare namespace IFundingRate {
  export type FundingFeeConfigStruct = {
    growthRate: BigNumberish;
    baseRate: BigNumberish;
    maxRate: BigNumberish;
    fundingInterval: BigNumberish;
  };

  export type FundingFeeConfigStructOutput = [
    growthRate: bigint,
    baseRate: bigint,
    maxRate: bigint,
    fundingInterval: bigint
  ] & {
    growthRate: bigint;
    baseRate: bigint;
    maxRate: bigint;
    fundingInterval: bigint;
  };

  export type FundingFeeConfigV2Struct = {
    growthRateLow: BigNumberish;
    growthRateHigh: BigNumberish;
    range: BigNumberish;
    maxRate: BigNumberish;
    fundingInterval: BigNumberish;
  };

  export type FundingFeeConfigV2StructOutput = [
    growthRateLow: bigint,
    growthRateHigh: bigint,
    range: bigint,
    maxRate: bigint,
    fundingInterval: bigint
  ] & {
    growthRateLow: bigint;
    growthRateHigh: bigint;
    range: bigint;
    maxRate: bigint;
    fundingInterval: bigint;
  };
}

export interface FundingRateInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADDRESS_PROVIDER"
      | "configurationProvider"
      | "fundingFeeConfigs"
      | "fundingFeeConfigsV2"
      | "getFundingInterval"
      | "getFundingRate"
      | "getFundingRateV2"
      | "initialize"
      | "proxiableUUID"
      | "updateConfigurationProviderAddress"
      | "updateFundingFeeConfig"
      | "updateFundingFeeConfigV2"
      | "upgradeTo"
      | "upgradeToAndCall"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminChanged"
      | "BeaconUpgraded"
      | "Initialized"
      | "UpdateConfigurationProviderAddress"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADDRESS_PROVIDER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "configurationProvider",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fundingFeeConfigs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fundingFeeConfigsV2",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFundingInterval",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFundingRate",
    values: [IPool.PairStruct, IPool.VaultStruct, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFundingRateV2",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateConfigurationProviderAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateFundingFeeConfig",
    values: [BigNumberish, IFundingRate.FundingFeeConfigStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "updateFundingFeeConfigV2",
    values: [BigNumberish, IFundingRate.FundingFeeConfigV2Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeTo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "ADDRESS_PROVIDER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "configurationProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundingFeeConfigs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundingFeeConfigsV2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFundingInterval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFundingRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFundingRateV2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateConfigurationProviderAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateFundingFeeConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateFundingFeeConfigV2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "upgradeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
}

export namespace AdminChangedEvent {
  export type InputTuple = [previousAdmin: AddressLike, newAdmin: AddressLike];
  export type OutputTuple = [previousAdmin: string, newAdmin: string];
  export interface OutputObject {
    previousAdmin: string;
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BeaconUpgradedEvent {
  export type InputTuple = [beacon: AddressLike];
  export type OutputTuple = [beacon: string];
  export interface OutputObject {
    beacon: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateConfigurationProviderAddressEvent {
  export type InputTuple = [
    sender: AddressLike,
    oldAddress: AddressLike,
    newAddress: AddressLike
  ];
  export type OutputTuple = [
    sender: string,
    oldAddress: string,
    newAddress: string
  ];
  export interface OutputObject {
    sender: string;
    oldAddress: string;
    newAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FundingRate extends BaseContract {
  connect(runner?: ContractRunner | null): FundingRate;
  waitForDeployment(): Promise<this>;

  interface: FundingRateInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADDRESS_PROVIDER: TypedContractMethod<[], [string], "view">;

  configurationProvider: TypedContractMethod<[], [string], "view">;

  fundingFeeConfigs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        growthRate: bigint;
        baseRate: bigint;
        maxRate: bigint;
        fundingInterval: bigint;
      }
    ],
    "view"
  >;

  fundingFeeConfigsV2: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        growthRateLow: bigint;
        growthRateHigh: bigint;
        range: bigint;
        maxRate: bigint;
        fundingInterval: bigint;
      }
    ],
    "view"
  >;

  getFundingInterval: TypedContractMethod<
    [_pairIndex: BigNumberish],
    [bigint],
    "view"
  >;

  getFundingRate: TypedContractMethod<
    [pair: IPool.PairStruct, vault: IPool.VaultStruct, price: BigNumberish],
    [bigint],
    "view"
  >;

  getFundingRateV2: TypedContractMethod<
    [pool: AddressLike, pairIndex: BigNumberish, price: BigNumberish],
    [bigint],
    "view"
  >;

  initialize: TypedContractMethod<
    [addressProvider: AddressLike],
    [void],
    "nonpayable"
  >;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  updateConfigurationProviderAddress: TypedContractMethod<
    [_configurationProvider: AddressLike],
    [void],
    "nonpayable"
  >;

  updateFundingFeeConfig: TypedContractMethod<
    [
      _pairIndex: BigNumberish,
      _fundingFeeConfig: IFundingRate.FundingFeeConfigStruct
    ],
    [void],
    "nonpayable"
  >;

  updateFundingFeeConfigV2: TypedContractMethod<
    [
      _pairIndex: BigNumberish,
      _fundingFeeConfig: IFundingRate.FundingFeeConfigV2Struct
    ],
    [void],
    "nonpayable"
  >;

  upgradeTo: TypedContractMethod<
    [newImplementation: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADDRESS_PROVIDER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "configurationProvider"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "fundingFeeConfigs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        growthRate: bigint;
        baseRate: bigint;
        maxRate: bigint;
        fundingInterval: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "fundingFeeConfigsV2"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        growthRateLow: bigint;
        growthRateHigh: bigint;
        range: bigint;
        maxRate: bigint;
        fundingInterval: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFundingInterval"
  ): TypedContractMethod<[_pairIndex: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getFundingRate"
  ): TypedContractMethod<
    [pair: IPool.PairStruct, vault: IPool.VaultStruct, price: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFundingRateV2"
  ): TypedContractMethod<
    [pool: AddressLike, pairIndex: BigNumberish, price: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[addressProvider: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "updateConfigurationProviderAddress"
  ): TypedContractMethod<
    [_configurationProvider: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateFundingFeeConfig"
  ): TypedContractMethod<
    [
      _pairIndex: BigNumberish,
      _fundingFeeConfig: IFundingRate.FundingFeeConfigStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateFundingFeeConfigV2"
  ): TypedContractMethod<
    [
      _pairIndex: BigNumberish,
      _fundingFeeConfig: IFundingRate.FundingFeeConfigV2Struct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeTo"
  ): TypedContractMethod<
    [newImplementation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getEvent(
    key: "AdminChanged"
  ): TypedContractEvent<
    AdminChangedEvent.InputTuple,
    AdminChangedEvent.OutputTuple,
    AdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "BeaconUpgraded"
  ): TypedContractEvent<
    BeaconUpgradedEvent.InputTuple,
    BeaconUpgradedEvent.OutputTuple,
    BeaconUpgradedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "UpdateConfigurationProviderAddress"
  ): TypedContractEvent<
    UpdateConfigurationProviderAddressEvent.InputTuple,
    UpdateConfigurationProviderAddressEvent.OutputTuple,
    UpdateConfigurationProviderAddressEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "AdminChanged(address,address)": TypedContractEvent<
      AdminChangedEvent.InputTuple,
      AdminChangedEvent.OutputTuple,
      AdminChangedEvent.OutputObject
    >;
    AdminChanged: TypedContractEvent<
      AdminChangedEvent.InputTuple,
      AdminChangedEvent.OutputTuple,
      AdminChangedEvent.OutputObject
    >;

    "BeaconUpgraded(address)": TypedContractEvent<
      BeaconUpgradedEvent.InputTuple,
      BeaconUpgradedEvent.OutputTuple,
      BeaconUpgradedEvent.OutputObject
    >;
    BeaconUpgraded: TypedContractEvent<
      BeaconUpgradedEvent.InputTuple,
      BeaconUpgradedEvent.OutputTuple,
      BeaconUpgradedEvent.OutputObject
    >;

    "Initialized(uint8)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "UpdateConfigurationProviderAddress(address,address,address)": TypedContractEvent<
      UpdateConfigurationProviderAddressEvent.InputTuple,
      UpdateConfigurationProviderAddressEvent.OutputTuple,
      UpdateConfigurationProviderAddressEvent.OutputObject
    >;
    UpdateConfigurationProviderAddress: TypedContractEvent<
      UpdateConfigurationProviderAddressEvent.InputTuple,
      UpdateConfigurationProviderAddressEvent.OutputTuple,
      UpdateConfigurationProviderAddressEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
