/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IRouter {
  export type AddOrderTpSlRequestStruct = {
    orderId: BigNumberish;
    tradeType: BigNumberish;
    tpPrice: BigNumberish;
    tp: BigNumberish;
    slPrice: BigNumberish;
    sl: BigNumberish;
    paymentType: BigNumberish;
    tpNetworkFeeAmount: BigNumberish;
    slNetworkFeeAmount: BigNumberish;
  };

  export type AddOrderTpSlRequestStructOutput = [
    orderId: bigint,
    tradeType: bigint,
    tpPrice: bigint,
    tp: bigint,
    slPrice: bigint,
    sl: bigint,
    paymentType: bigint,
    tpNetworkFeeAmount: bigint,
    slNetworkFeeAmount: bigint
  ] & {
    orderId: bigint;
    tradeType: bigint;
    tpPrice: bigint;
    tp: bigint;
    slPrice: bigint;
    sl: bigint;
    paymentType: bigint;
    tpNetworkFeeAmount: bigint;
    slNetworkFeeAmount: bigint;
  };

  export type CancelOrderRequestStruct = {
    orderId: BigNumberish;
    tradeType: BigNumberish;
    isIncrease: boolean;
  };

  export type CancelOrderRequestStructOutput = [
    orderId: bigint,
    tradeType: bigint,
    isIncrease: boolean
  ] & { orderId: bigint; tradeType: bigint; isIncrease: boolean };

  export type OperationStatusStruct = {
    increasePositionDisabled: boolean;
    decreasePositionDisabled: boolean;
    orderDisabled: boolean;
    addLiquidityDisabled: boolean;
    removeLiquidityDisabled: boolean;
  };

  export type OperationStatusStructOutput = [
    increasePositionDisabled: boolean,
    decreasePositionDisabled: boolean,
    orderDisabled: boolean,
    addLiquidityDisabled: boolean,
    removeLiquidityDisabled: boolean
  ] & {
    increasePositionDisabled: boolean;
    decreasePositionDisabled: boolean;
    orderDisabled: boolean;
    addLiquidityDisabled: boolean;
    removeLiquidityDisabled: boolean;
  };
}

export declare namespace TradingTypes {
  export type DecreasePositionRequestStruct = {
    account: AddressLike;
    pairIndex: BigNumberish;
    tradeType: BigNumberish;
    collateral: BigNumberish;
    triggerPrice: BigNumberish;
    sizeAmount: BigNumberish;
    isLong: boolean;
    maxSlippage: BigNumberish;
    paymentType: BigNumberish;
    networkFeeAmount: BigNumberish;
  };

  export type DecreasePositionRequestStructOutput = [
    account: string,
    pairIndex: bigint,
    tradeType: bigint,
    collateral: bigint,
    triggerPrice: bigint,
    sizeAmount: bigint,
    isLong: boolean,
    maxSlippage: bigint,
    paymentType: bigint,
    networkFeeAmount: bigint
  ] & {
    account: string;
    pairIndex: bigint;
    tradeType: bigint;
    collateral: bigint;
    triggerPrice: bigint;
    sizeAmount: bigint;
    isLong: boolean;
    maxSlippage: bigint;
    paymentType: bigint;
    networkFeeAmount: bigint;
  };

  export type IncreasePositionRequestStruct = {
    account: AddressLike;
    pairIndex: BigNumberish;
    tradeType: BigNumberish;
    collateral: BigNumberish;
    openPrice: BigNumberish;
    isLong: boolean;
    sizeAmount: BigNumberish;
    maxSlippage: BigNumberish;
    paymentType: BigNumberish;
    networkFeeAmount: BigNumberish;
  };

  export type IncreasePositionRequestStructOutput = [
    account: string,
    pairIndex: bigint,
    tradeType: bigint,
    collateral: bigint,
    openPrice: bigint,
    isLong: boolean,
    sizeAmount: bigint,
    maxSlippage: bigint,
    paymentType: bigint,
    networkFeeAmount: bigint
  ] & {
    account: string;
    pairIndex: bigint;
    tradeType: bigint;
    collateral: bigint;
    openPrice: bigint;
    isLong: boolean;
    sizeAmount: bigint;
    maxSlippage: bigint;
    paymentType: bigint;
    networkFeeAmount: bigint;
  };

  export type IncreasePositionWithTpSlRequestStruct = {
    account: AddressLike;
    pairIndex: BigNumberish;
    tradeType: BigNumberish;
    collateral: BigNumberish;
    openPrice: BigNumberish;
    isLong: boolean;
    sizeAmount: BigNumberish;
    tpPrice: BigNumberish;
    tp: BigNumberish;
    slPrice: BigNumberish;
    sl: BigNumberish;
    maxSlippage: BigNumberish;
    paymentType: BigNumberish;
    networkFeeAmount: BigNumberish;
    tpNetworkFeeAmount: BigNumberish;
    slNetworkFeeAmount: BigNumberish;
  };

  export type IncreasePositionWithTpSlRequestStructOutput = [
    account: string,
    pairIndex: bigint,
    tradeType: bigint,
    collateral: bigint,
    openPrice: bigint,
    isLong: boolean,
    sizeAmount: bigint,
    tpPrice: bigint,
    tp: bigint,
    slPrice: bigint,
    sl: bigint,
    maxSlippage: bigint,
    paymentType: bigint,
    networkFeeAmount: bigint,
    tpNetworkFeeAmount: bigint,
    slNetworkFeeAmount: bigint
  ] & {
    account: string;
    pairIndex: bigint;
    tradeType: bigint;
    collateral: bigint;
    openPrice: bigint;
    isLong: boolean;
    sizeAmount: bigint;
    tpPrice: bigint;
    tp: bigint;
    slPrice: bigint;
    sl: bigint;
    maxSlippage: bigint;
    paymentType: bigint;
    networkFeeAmount: bigint;
    tpNetworkFeeAmount: bigint;
    slNetworkFeeAmount: bigint;
  };

  export type CreateTpSlRequestStruct = {
    account: AddressLike;
    pairIndex: BigNumberish;
    isLong: boolean;
    tpPrice: BigNumberish;
    tp: BigNumberish;
    slPrice: BigNumberish;
    sl: BigNumberish;
    paymentType: BigNumberish;
    tpNetworkFeeAmount: BigNumberish;
    slNetworkFeeAmount: BigNumberish;
  };

  export type CreateTpSlRequestStructOutput = [
    account: string,
    pairIndex: bigint,
    isLong: boolean,
    tpPrice: bigint,
    tp: bigint,
    slPrice: bigint,
    sl: bigint,
    paymentType: bigint,
    tpNetworkFeeAmount: bigint,
    slNetworkFeeAmount: bigint
  ] & {
    account: string;
    pairIndex: bigint;
    isLong: boolean;
    tpPrice: bigint;
    tp: bigint;
    slPrice: bigint;
    sl: bigint;
    paymentType: bigint;
    tpNetworkFeeAmount: bigint;
    slNetworkFeeAmount: bigint;
  };
}

export interface RouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADDRESS_PROVIDER"
      | "addLiquidity"
      | "addLiquidityCallback"
      | "addLiquidityETH"
      | "addLiquidityForAccount"
      | "addOrderTpSl"
      | "cancelOrder"
      | "cancelOrders"
      | "cancelPositionOrders"
      | "createDecreaseOrder"
      | "createDecreaseOrders"
      | "createIncreaseOrder"
      | "createIncreaseOrderWithTpSl"
      | "createOrderCallback"
      | "createTpSl"
      | "getOperationStatus"
      | "multicall"
      | "operationStatus"
      | "orderManager"
      | "paused"
      | "pool"
      | "positionManager"
      | "removeLiquidity"
      | "removeLiquidityCallback"
      | "removeLiquidityForAccount"
      | "salvageToken"
      | "setPaused"
      | "setPriceAndAdjustCollateral"
      | "setPriceAndUpdateFundingRate"
      | "setUnPaused"
      | "updateAddLiquidityStatus"
      | "updateDecreasePositionStatus"
      | "updateIncreasePositionStatus"
      | "updateOrderStatus"
      | "updateRemoveLiquidityStatus"
      | "wrapWETH"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Paused"
      | "Unpaused"
      | "UpdateAddLiquidityStatus"
      | "UpdateDecreasePositionStatus"
      | "UpdateIncreasePositionStatus"
      | "UpdateOrderStatus"
      | "UpdateRemoveLiquidityStatus"
      | "UpdateTradingRouter"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADDRESS_PROVIDER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addLiquidity",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      AddressLike[],
      BytesLike[],
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "addLiquidityCallback",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addLiquidityETH",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      AddressLike[],
      BytesLike[],
      BigNumberish[],
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "addLiquidityForAccount",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      AddressLike[],
      BytesLike[],
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "addOrderTpSl",
    values: [IRouter.AddOrderTpSlRequestStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelOrder",
    values: [IRouter.CancelOrderRequestStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelOrders",
    values: [IRouter.CancelOrderRequestStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelPositionOrders",
    values: [BigNumberish, boolean, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "createDecreaseOrder",
    values: [TradingTypes.DecreasePositionRequestStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "createDecreaseOrders",
    values: [TradingTypes.DecreasePositionRequestStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "createIncreaseOrder",
    values: [TradingTypes.IncreasePositionRequestStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "createIncreaseOrderWithTpSl",
    values: [TradingTypes.IncreasePositionWithTpSlRequestStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "createOrderCallback",
    values: [AddressLike, BigNumberish, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createTpSl",
    values: [TradingTypes.CreateTpSlRequestStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getOperationStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "multicall",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "operationStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "orderManager",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(functionFragment: "pool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "positionManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeLiquidity",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      boolean,
      AddressLike[],
      BytesLike[],
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "removeLiquidityCallback",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeLiquidityForAccount",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      boolean,
      AddressLike[],
      BytesLike[],
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "salvageToken",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "setPaused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setPriceAndAdjustCollateral",
    values: [
      BigNumberish,
      boolean,
      BigNumberish,
      AddressLike[],
      BytesLike[],
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setPriceAndUpdateFundingRate",
    values: [BigNumberish, AddressLike[], BytesLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setUnPaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateAddLiquidityStatus",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "updateDecreasePositionStatus",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "updateIncreasePositionStatus",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "updateOrderStatus",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRemoveLiquidityStatus",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "wrapWETH",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "ADDRESS_PROVIDER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addLiquidityCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addLiquidityETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addLiquidityForAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addOrderTpSl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelPositionOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createDecreaseOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createDecreaseOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createIncreaseOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createIncreaseOrderWithTpSl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createOrderCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createTpSl", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getOperationStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "multicall", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "operationStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "orderManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "positionManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeLiquidityCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeLiquidityForAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "salvageToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPaused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPriceAndAdjustCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPriceAndUpdateFundingRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUnPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAddLiquidityStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateDecreasePositionStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateIncreasePositionStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateOrderStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRemoveLiquidityStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "wrapWETH", data: BytesLike): Result;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateAddLiquidityStatusEvent {
  export type InputTuple = [
    sender: AddressLike,
    pairIndex: BigNumberish,
    enabled: boolean
  ];
  export type OutputTuple = [
    sender: string,
    pairIndex: bigint,
    enabled: boolean
  ];
  export interface OutputObject {
    sender: string;
    pairIndex: bigint;
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateDecreasePositionStatusEvent {
  export type InputTuple = [
    sender: AddressLike,
    pairIndex: BigNumberish,
    enabled: boolean
  ];
  export type OutputTuple = [
    sender: string,
    pairIndex: bigint,
    enabled: boolean
  ];
  export interface OutputObject {
    sender: string;
    pairIndex: bigint;
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateIncreasePositionStatusEvent {
  export type InputTuple = [
    sender: AddressLike,
    pairIndex: BigNumberish,
    enabled: boolean
  ];
  export type OutputTuple = [
    sender: string,
    pairIndex: bigint,
    enabled: boolean
  ];
  export interface OutputObject {
    sender: string;
    pairIndex: bigint;
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateOrderStatusEvent {
  export type InputTuple = [
    sender: AddressLike,
    pairIndex: BigNumberish,
    enabled: boolean
  ];
  export type OutputTuple = [
    sender: string,
    pairIndex: bigint,
    enabled: boolean
  ];
  export interface OutputObject {
    sender: string;
    pairIndex: bigint;
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateRemoveLiquidityStatusEvent {
  export type InputTuple = [
    sender: AddressLike,
    pairIndex: BigNumberish,
    enabled: boolean
  ];
  export type OutputTuple = [
    sender: string,
    pairIndex: bigint,
    enabled: boolean
  ];
  export interface OutputObject {
    sender: string;
    pairIndex: bigint;
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateTradingRouterEvent {
  export type InputTuple = [oldAddress: AddressLike, newAddress: AddressLike];
  export type OutputTuple = [oldAddress: string, newAddress: string];
  export interface OutputObject {
    oldAddress: string;
    newAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Router extends BaseContract {
  connect(runner?: ContractRunner | null): Router;
  waitForDeployment(): Promise<this>;

  interface: RouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADDRESS_PROVIDER: TypedContractMethod<[], [string], "view">;

  addLiquidity: TypedContractMethod<
    [
      indexToken: AddressLike,
      stableToken: AddressLike,
      indexAmount: BigNumberish,
      stableAmount: BigNumberish,
      tokens: AddressLike[],
      updateData: BytesLike[],
      publishTimes: BigNumberish[]
    ],
    [
      [bigint, string, bigint] & {
        mintAmount: bigint;
        slipToken: string;
        slipAmount: bigint;
      }
    ],
    "payable"
  >;

  addLiquidityCallback: TypedContractMethod<
    [
      indexToken: AddressLike,
      stableToken: AddressLike,
      amountIndex: BigNumberish,
      amountStable: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  addLiquidityETH: TypedContractMethod<
    [
      indexToken: AddressLike,
      stableToken: AddressLike,
      indexAmount: BigNumberish,
      stableAmount: BigNumberish,
      tokens: AddressLike[],
      updateData: BytesLike[],
      publishTimes: BigNumberish[],
      updateFee: BigNumberish
    ],
    [
      [bigint, string, bigint] & {
        mintAmount: bigint;
        slipToken: string;
        slipAmount: bigint;
      }
    ],
    "payable"
  >;

  addLiquidityForAccount: TypedContractMethod<
    [
      indexToken: AddressLike,
      stableToken: AddressLike,
      receiver: AddressLike,
      indexAmount: BigNumberish,
      stableAmount: BigNumberish,
      tokens: AddressLike[],
      updateData: BytesLike[],
      publishTimes: BigNumberish[]
    ],
    [
      [bigint, string, bigint] & {
        mintAmount: bigint;
        slipToken: string;
        slipAmount: bigint;
      }
    ],
    "payable"
  >;

  addOrderTpSl: TypedContractMethod<
    [request: IRouter.AddOrderTpSlRequestStruct],
    [void],
    "payable"
  >;

  cancelOrder: TypedContractMethod<
    [request: IRouter.CancelOrderRequestStruct],
    [void],
    "nonpayable"
  >;

  cancelOrders: TypedContractMethod<
    [requests: IRouter.CancelOrderRequestStruct[]],
    [void],
    "nonpayable"
  >;

  cancelPositionOrders: TypedContractMethod<
    [pairIndex: BigNumberish, isLong: boolean, isIncrease: boolean],
    [void],
    "nonpayable"
  >;

  createDecreaseOrder: TypedContractMethod<
    [request: TradingTypes.DecreasePositionRequestStruct],
    [bigint],
    "payable"
  >;

  createDecreaseOrders: TypedContractMethod<
    [requests: TradingTypes.DecreasePositionRequestStruct[]],
    [bigint[]],
    "payable"
  >;

  createIncreaseOrder: TypedContractMethod<
    [request: TradingTypes.IncreasePositionRequestStruct],
    [bigint],
    "payable"
  >;

  createIncreaseOrderWithTpSl: TypedContractMethod<
    [request: TradingTypes.IncreasePositionWithTpSlRequestStruct],
    [bigint],
    "payable"
  >;

  createOrderCallback: TypedContractMethod<
    [
      collateral: AddressLike,
      amount: BigNumberish,
      to: AddressLike,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  createTpSl: TypedContractMethod<
    [request: TradingTypes.CreateTpSlRequestStruct],
    [[bigint, bigint] & { tpOrderId: bigint; slOrderId: bigint }],
    "payable"
  >;

  getOperationStatus: TypedContractMethod<
    [pairIndex: BigNumberish],
    [IRouter.OperationStatusStructOutput],
    "view"
  >;

  multicall: TypedContractMethod<[data: BytesLike[]], [string[]], "payable">;

  operationStatus: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [boolean, boolean, boolean, boolean, boolean] & {
        increasePositionDisabled: boolean;
        decreasePositionDisabled: boolean;
        orderDisabled: boolean;
        addLiquidityDisabled: boolean;
        removeLiquidityDisabled: boolean;
      }
    ],
    "view"
  >;

  orderManager: TypedContractMethod<[], [string], "view">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pool: TypedContractMethod<[], [string], "view">;

  positionManager: TypedContractMethod<[], [string], "view">;

  removeLiquidity: TypedContractMethod<
    [
      indexToken: AddressLike,
      stableToken: AddressLike,
      amount: BigNumberish,
      useETH: boolean,
      tokens: AddressLike[],
      updateData: BytesLike[],
      publishTimes: BigNumberish[]
    ],
    [
      [bigint, bigint, bigint] & {
        receivedIndexAmount: bigint;
        receivedStableAmount: bigint;
        feeAmount: bigint;
      }
    ],
    "payable"
  >;

  removeLiquidityCallback: TypedContractMethod<
    [pairToken: AddressLike, amount: BigNumberish, data: BytesLike],
    [void],
    "nonpayable"
  >;

  removeLiquidityForAccount: TypedContractMethod<
    [
      indexToken: AddressLike,
      stableToken: AddressLike,
      receiver: AddressLike,
      amount: BigNumberish,
      useETH: boolean,
      tokens: AddressLike[],
      updateData: BytesLike[],
      publishTimes: BigNumberish[]
    ],
    [
      [bigint, bigint, bigint] & {
        receivedIndexAmount: bigint;
        receivedStableAmount: bigint;
        feeAmount: bigint;
      }
    ],
    "payable"
  >;

  salvageToken: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPaused: TypedContractMethod<[], [void], "nonpayable">;

  setPriceAndAdjustCollateral: TypedContractMethod<
    [
      pairIndex: BigNumberish,
      isLong: boolean,
      collateral: BigNumberish,
      tokens: AddressLike[],
      updateData: BytesLike[],
      publishTimes: BigNumberish[]
    ],
    [void],
    "payable"
  >;

  setPriceAndUpdateFundingRate: TypedContractMethod<
    [
      pairIndex: BigNumberish,
      tokens: AddressLike[],
      updateData: BytesLike[],
      publishTimes: BigNumberish[]
    ],
    [void],
    "payable"
  >;

  setUnPaused: TypedContractMethod<[], [void], "nonpayable">;

  updateAddLiquidityStatus: TypedContractMethod<
    [pairIndex: BigNumberish, enabled: boolean],
    [void],
    "nonpayable"
  >;

  updateDecreasePositionStatus: TypedContractMethod<
    [pairIndex: BigNumberish, enabled: boolean],
    [void],
    "nonpayable"
  >;

  updateIncreasePositionStatus: TypedContractMethod<
    [pairIndex: BigNumberish, enabled: boolean],
    [void],
    "nonpayable"
  >;

  updateOrderStatus: TypedContractMethod<
    [pairIndex: BigNumberish, enabled: boolean],
    [void],
    "nonpayable"
  >;

  updateRemoveLiquidityStatus: TypedContractMethod<
    [pairIndex: BigNumberish, enabled: boolean],
    [void],
    "nonpayable"
  >;

  wrapWETH: TypedContractMethod<[recipient: AddressLike], [void], "payable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADDRESS_PROVIDER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addLiquidity"
  ): TypedContractMethod<
    [
      indexToken: AddressLike,
      stableToken: AddressLike,
      indexAmount: BigNumberish,
      stableAmount: BigNumberish,
      tokens: AddressLike[],
      updateData: BytesLike[],
      publishTimes: BigNumberish[]
    ],
    [
      [bigint, string, bigint] & {
        mintAmount: bigint;
        slipToken: string;
        slipAmount: bigint;
      }
    ],
    "payable"
  >;
  getFunction(
    nameOrSignature: "addLiquidityCallback"
  ): TypedContractMethod<
    [
      indexToken: AddressLike,
      stableToken: AddressLike,
      amountIndex: BigNumberish,
      amountStable: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addLiquidityETH"
  ): TypedContractMethod<
    [
      indexToken: AddressLike,
      stableToken: AddressLike,
      indexAmount: BigNumberish,
      stableAmount: BigNumberish,
      tokens: AddressLike[],
      updateData: BytesLike[],
      publishTimes: BigNumberish[],
      updateFee: BigNumberish
    ],
    [
      [bigint, string, bigint] & {
        mintAmount: bigint;
        slipToken: string;
        slipAmount: bigint;
      }
    ],
    "payable"
  >;
  getFunction(
    nameOrSignature: "addLiquidityForAccount"
  ): TypedContractMethod<
    [
      indexToken: AddressLike,
      stableToken: AddressLike,
      receiver: AddressLike,
      indexAmount: BigNumberish,
      stableAmount: BigNumberish,
      tokens: AddressLike[],
      updateData: BytesLike[],
      publishTimes: BigNumberish[]
    ],
    [
      [bigint, string, bigint] & {
        mintAmount: bigint;
        slipToken: string;
        slipAmount: bigint;
      }
    ],
    "payable"
  >;
  getFunction(
    nameOrSignature: "addOrderTpSl"
  ): TypedContractMethod<
    [request: IRouter.AddOrderTpSlRequestStruct],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "cancelOrder"
  ): TypedContractMethod<
    [request: IRouter.CancelOrderRequestStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelOrders"
  ): TypedContractMethod<
    [requests: IRouter.CancelOrderRequestStruct[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelPositionOrders"
  ): TypedContractMethod<
    [pairIndex: BigNumberish, isLong: boolean, isIncrease: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createDecreaseOrder"
  ): TypedContractMethod<
    [request: TradingTypes.DecreasePositionRequestStruct],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "createDecreaseOrders"
  ): TypedContractMethod<
    [requests: TradingTypes.DecreasePositionRequestStruct[]],
    [bigint[]],
    "payable"
  >;
  getFunction(
    nameOrSignature: "createIncreaseOrder"
  ): TypedContractMethod<
    [request: TradingTypes.IncreasePositionRequestStruct],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "createIncreaseOrderWithTpSl"
  ): TypedContractMethod<
    [request: TradingTypes.IncreasePositionWithTpSlRequestStruct],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "createOrderCallback"
  ): TypedContractMethod<
    [
      collateral: AddressLike,
      amount: BigNumberish,
      to: AddressLike,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createTpSl"
  ): TypedContractMethod<
    [request: TradingTypes.CreateTpSlRequestStruct],
    [[bigint, bigint] & { tpOrderId: bigint; slOrderId: bigint }],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getOperationStatus"
  ): TypedContractMethod<
    [pairIndex: BigNumberish],
    [IRouter.OperationStatusStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "multicall"
  ): TypedContractMethod<[data: BytesLike[]], [string[]], "payable">;
  getFunction(
    nameOrSignature: "operationStatus"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [boolean, boolean, boolean, boolean, boolean] & {
        increasePositionDisabled: boolean;
        decreasePositionDisabled: boolean;
        orderDisabled: boolean;
        addLiquidityDisabled: boolean;
        removeLiquidityDisabled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "orderManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "positionManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeLiquidity"
  ): TypedContractMethod<
    [
      indexToken: AddressLike,
      stableToken: AddressLike,
      amount: BigNumberish,
      useETH: boolean,
      tokens: AddressLike[],
      updateData: BytesLike[],
      publishTimes: BigNumberish[]
    ],
    [
      [bigint, bigint, bigint] & {
        receivedIndexAmount: bigint;
        receivedStableAmount: bigint;
        feeAmount: bigint;
      }
    ],
    "payable"
  >;
  getFunction(
    nameOrSignature: "removeLiquidityCallback"
  ): TypedContractMethod<
    [pairToken: AddressLike, amount: BigNumberish, data: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeLiquidityForAccount"
  ): TypedContractMethod<
    [
      indexToken: AddressLike,
      stableToken: AddressLike,
      receiver: AddressLike,
      amount: BigNumberish,
      useETH: boolean,
      tokens: AddressLike[],
      updateData: BytesLike[],
      publishTimes: BigNumberish[]
    ],
    [
      [bigint, bigint, bigint] & {
        receivedIndexAmount: bigint;
        receivedStableAmount: bigint;
        feeAmount: bigint;
      }
    ],
    "payable"
  >;
  getFunction(
    nameOrSignature: "salvageToken"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPaused"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPriceAndAdjustCollateral"
  ): TypedContractMethod<
    [
      pairIndex: BigNumberish,
      isLong: boolean,
      collateral: BigNumberish,
      tokens: AddressLike[],
      updateData: BytesLike[],
      publishTimes: BigNumberish[]
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "setPriceAndUpdateFundingRate"
  ): TypedContractMethod<
    [
      pairIndex: BigNumberish,
      tokens: AddressLike[],
      updateData: BytesLike[],
      publishTimes: BigNumberish[]
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "setUnPaused"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateAddLiquidityStatus"
  ): TypedContractMethod<
    [pairIndex: BigNumberish, enabled: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateDecreasePositionStatus"
  ): TypedContractMethod<
    [pairIndex: BigNumberish, enabled: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateIncreasePositionStatus"
  ): TypedContractMethod<
    [pairIndex: BigNumberish, enabled: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateOrderStatus"
  ): TypedContractMethod<
    [pairIndex: BigNumberish, enabled: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateRemoveLiquidityStatus"
  ): TypedContractMethod<
    [pairIndex: BigNumberish, enabled: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "wrapWETH"
  ): TypedContractMethod<[recipient: AddressLike], [void], "payable">;

  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "UpdateAddLiquidityStatus"
  ): TypedContractEvent<
    UpdateAddLiquidityStatusEvent.InputTuple,
    UpdateAddLiquidityStatusEvent.OutputTuple,
    UpdateAddLiquidityStatusEvent.OutputObject
  >;
  getEvent(
    key: "UpdateDecreasePositionStatus"
  ): TypedContractEvent<
    UpdateDecreasePositionStatusEvent.InputTuple,
    UpdateDecreasePositionStatusEvent.OutputTuple,
    UpdateDecreasePositionStatusEvent.OutputObject
  >;
  getEvent(
    key: "UpdateIncreasePositionStatus"
  ): TypedContractEvent<
    UpdateIncreasePositionStatusEvent.InputTuple,
    UpdateIncreasePositionStatusEvent.OutputTuple,
    UpdateIncreasePositionStatusEvent.OutputObject
  >;
  getEvent(
    key: "UpdateOrderStatus"
  ): TypedContractEvent<
    UpdateOrderStatusEvent.InputTuple,
    UpdateOrderStatusEvent.OutputTuple,
    UpdateOrderStatusEvent.OutputObject
  >;
  getEvent(
    key: "UpdateRemoveLiquidityStatus"
  ): TypedContractEvent<
    UpdateRemoveLiquidityStatusEvent.InputTuple,
    UpdateRemoveLiquidityStatusEvent.OutputTuple,
    UpdateRemoveLiquidityStatusEvent.OutputObject
  >;
  getEvent(
    key: "UpdateTradingRouter"
  ): TypedContractEvent<
    UpdateTradingRouterEvent.InputTuple,
    UpdateTradingRouterEvent.OutputTuple,
    UpdateTradingRouterEvent.OutputObject
  >;

  filters: {
    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "UpdateAddLiquidityStatus(address,uint256,bool)": TypedContractEvent<
      UpdateAddLiquidityStatusEvent.InputTuple,
      UpdateAddLiquidityStatusEvent.OutputTuple,
      UpdateAddLiquidityStatusEvent.OutputObject
    >;
    UpdateAddLiquidityStatus: TypedContractEvent<
      UpdateAddLiquidityStatusEvent.InputTuple,
      UpdateAddLiquidityStatusEvent.OutputTuple,
      UpdateAddLiquidityStatusEvent.OutputObject
    >;

    "UpdateDecreasePositionStatus(address,uint256,bool)": TypedContractEvent<
      UpdateDecreasePositionStatusEvent.InputTuple,
      UpdateDecreasePositionStatusEvent.OutputTuple,
      UpdateDecreasePositionStatusEvent.OutputObject
    >;
    UpdateDecreasePositionStatus: TypedContractEvent<
      UpdateDecreasePositionStatusEvent.InputTuple,
      UpdateDecreasePositionStatusEvent.OutputTuple,
      UpdateDecreasePositionStatusEvent.OutputObject
    >;

    "UpdateIncreasePositionStatus(address,uint256,bool)": TypedContractEvent<
      UpdateIncreasePositionStatusEvent.InputTuple,
      UpdateIncreasePositionStatusEvent.OutputTuple,
      UpdateIncreasePositionStatusEvent.OutputObject
    >;
    UpdateIncreasePositionStatus: TypedContractEvent<
      UpdateIncreasePositionStatusEvent.InputTuple,
      UpdateIncreasePositionStatusEvent.OutputTuple,
      UpdateIncreasePositionStatusEvent.OutputObject
    >;

    "UpdateOrderStatus(address,uint256,bool)": TypedContractEvent<
      UpdateOrderStatusEvent.InputTuple,
      UpdateOrderStatusEvent.OutputTuple,
      UpdateOrderStatusEvent.OutputObject
    >;
    UpdateOrderStatus: TypedContractEvent<
      UpdateOrderStatusEvent.InputTuple,
      UpdateOrderStatusEvent.OutputTuple,
      UpdateOrderStatusEvent.OutputObject
    >;

    "UpdateRemoveLiquidityStatus(address,uint256,bool)": TypedContractEvent<
      UpdateRemoveLiquidityStatusEvent.InputTuple,
      UpdateRemoveLiquidityStatusEvent.OutputTuple,
      UpdateRemoveLiquidityStatusEvent.OutputObject
    >;
    UpdateRemoveLiquidityStatus: TypedContractEvent<
      UpdateRemoveLiquidityStatusEvent.InputTuple,
      UpdateRemoveLiquidityStatusEvent.OutputTuple,
      UpdateRemoveLiquidityStatusEvent.OutputObject
    >;

    "UpdateTradingRouter(address,address)": TypedContractEvent<
      UpdateTradingRouterEvent.InputTuple,
      UpdateTradingRouterEvent.OutputTuple,
      UpdateTradingRouterEvent.OutputObject
    >;
    UpdateTradingRouter: TypedContractEvent<
      UpdateTradingRouterEvent.InputTuple,
      UpdateTradingRouterEvent.OutputTuple,
      UpdateTradingRouterEvent.OutputObject
    >;
  };
}
